version = 0.1

[default.deploy.parameters]
stack_name = "issue-tracker"
resolve_s3 = true
s3_prefix = "issue-tracker"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "af-south-1"
